### ISSUE TITLE
[BUG] - Broken conversion when dealing with simple geometry involving spheres

### ISSUE THREAD

**Issue by dodu94** [GEOUNED-org/GEOUNED#134]
# Describe the bug
It appears that the current version of geouned cannot completely deal with spheres. Here is a minimal geometrical example:

![image](https://github.com/GEOUNED-org/GEOUNED/assets/25747626/758bf6fe-1270-4342-b078-970f10b2a1db)

The internal body is well converted, while the external one is split in many solids that are then united together (instead of intersected?):
![image](https://github.com/GEOUNED-org/GEOUNED/assets/25747626/7c1f492f-b54f-4254-83db-d3278e3d896b)

to conclude, a screenshot of the MCNP cell definition:

![image](https://github.com/GEOUNED-org/GEOUNED/assets/25747626/86043e96-1bc8-4ff8-8ddd-e34e7cbc17d0)

# To Reproduce
Step file, config.ini file and results of the conversion can be found in the following zip file
[bug.zip](https://github.com/GEOUNED-org/GEOUNED/files/15247568/bug.zip)

# Please complete the following information):
 - OS: [e.g. Linux or Windows]: Windows 10
 - GEOUNED version: current main branch
 - Python version: Python from FreeCad v0.21.0 distribution

**Comment by psauvan** [comment]
This is not a GEOUNED bug, but a FreeCAD problem reading the stp file.
<img width="187" alt="FreeCAD" src="https://github.com/GEOUNED-org/GEOUNED/assets/20282428/c610dcae-af48-4489-8db0-4fdbd32e5dd8">
This picture is the original stp file opened with FreeCAD. After saving once more the file to step, the final file was traduced correclty (and opened well with FreeCAD)
  
[minimum_bug2.zip](https://github.com/GEOUNED-org/GEOUNED/files/15293334/minimum_bug2.zip)
