### ISSUE TITLE
Employ logging module for output logs

### ISSUE THREAD

**Issue by alberto743** [GEOUNED-org/GEOUNED#142]
GEOUNED generates several output log file with information about the conversion progress.
The mechanics of generating these files is not implemented via direct write statement.
Instead, it would be better to employ one of the following options:
1. `logging` module, in which a separate logger is open for each data file. This has the benefit of employing a standard module, which also share a global mechanisms to get the logger instance.
2. `io.StringIO` class, which saves all the data and dump everything to file at the end.
The preferred method is the former.
This should be applied to all output log, e.g. fuzzySurfaces.

**Comment by alberto743** [comment]
@shimwell, is this already fixed by `loggers`?  If yes, @psauvan may close this.

**Comment by alexvalentine94** [comment]
done
