### ISSUE TITLE
[BUG] - error PlaneParams object has no attribute dim1

### ISSUE THREAD

**Issue by shimwell** [GEOUNED-org/GEOUNED#154]
# Describe the bug
PlaneParams object has no attribute dim1 and this is accessed when the Tolerances.relativeTol is set to True

![Screenshot 2024-05-14 104623](https://github.com/GEOUNED-org/GEOUNED/assets/8583900/bfd07920-1fdb-4850-8b43-aed86cffdde5)

# To Reproduce
for example:
make a model where the is_same_plane method gets called and set Tolerances.relativeTol to True

# Expected behavior
the code should not access no existence attributes and should not crash

# Please complete the following information):
 - OS: [e.g. Linux or Windows] all OS systems
 - GEOUNED version dev and main
 - Python version 3.11

**Comment by psauvan** [comment]
here the correct attributes of ```PlaneParams``` class are ```dimL1``` and ```dimL2```
