### ISSUE TITLE
[BUG] - "sort_enclosure": true does not work properly

### ISSUE THREAD

**Issue by davideflammini** [GEOUNED-org/GEOUNED#254]
When "sort_enclosure": true is selected the enclosure cell(s) is repeated twice in the MCNP input file, using the same cell numbering. If one copy of the cell(s) is manually cancelled from the MCNP input, the geometry still presents  errors that are not present when "sort_enclosure": false is set. The geometry errors are due to a wrong sense of some of the surfaces used in the cell description of the enclosure. 

Enclosure is written in cell #4 of the attached examples and should be defined as follows:

4     0      -3 4 8 11 -12 -5 (15:14:-13)

It is instead defines as follows when "sort_enclosure": true:

C ##########################################################
C              ENCLOSURE 1
C ##########################################################
C 
4     0      3 4 8 11 12 -5 (15:14:-13)
           imp:n=1.0   imp:p=1.0   

 - OS: Windows
 - GEOUNED 1.2.0
 - Python version 3.11

In attachment: step file used for the test, MCNP inputs obtained with "sort_enclosure": true and "sort_enclosure": false
[sort_enclosure_false.txt](https://github.com/user-attachments/files/16179571/sort_enclosure_false.txt)
[sort_enclosure_true.txt](https://github.com/user-attachments/files/16179572/sort_enclosure_true.txt)
[step_file.zip](https://github.com/user-attachments/files/16179592/step_file.zip)

**Comment by psauvan** [comment]
bug fixed PR #255
