### ISSUE TITLE
[Feature request] - Continuous integration testing with Pytest

### ISSUE THREAD

**Issue by shimwell** [GEOUNED-org/GEOUNED#46]
There is a nice opportunity to add some CI to this repo and test the code as it gets updated.

A non exhaustive list of things that could be tested

- [x] installation routes to check the software can always be installed
- [x] conversion of CAD to mcnp, serpent, phits and openmc
- [ ] public CI based simulation is not possible for mcnp and serpent due to license but we could do still add the pytests and make the local testing easier for devs
- [x] compare csg text files with previously made csg text files that we know work in simulation (regression test)
- [x] conversion of CAD to openmc
- [x] simulation of openmc files and check result with manually made geometry that matches the CAD or DAGMC geometry ([perhaps similar to model benchmark zoo](https://github.com/fusion-energy/model_benchmark_zoo/))
- [x] test different python versions
- [x] test use with different operating systems
- [x] test with different methods of installing and connecting with freecad
- [ ] unit tests for functionality of code
- [x] regression tests to make sure we still get the same outputs

I'm keen to contribute the above todo list if allowed.

Just raising an issue to check if others are keen on seeing this testing added?

I've made a start over [here](https://github.com/shimwell/GEOUNED/pull/3) if anyone is interested

**Comment by shimwell** [comment]
Perhaps this package is useful for the performance testing
https://github.com/ionelmc/pytest-benchmark

**Comment by alberto743** [comment]
In my humble opinion, software performance shall not be put as a priority.
As Donald Knuth says, "premature optimization is the root of all evil".

More specifically, we need instead to have object persistence (e.g. via `pickle`) to let the user interactively save the state of partially converted models.
At the same time, the correctness of the conversions shall be verified against specific unit and integral test cases, to have as a top priority the reliability of the results.
Continuous integration pipelines should trigger a battery of fast test cases capable of covering the features of the software.

**Comment by alexvalentine94** [comment]
Closing as mostly completed
