### ISSUE TITLE
[BUG] - Bad units used in OpenMC files

### ISSUE THREAD

**Issue by ecasglez** [GEOUNED-org/GEOUNED#50]
# Describe the bug

I have prepared a FreeCAD file consisting of a cylinder with a radius of 50 mm and a height of 50 mm.
Then I exported the file to a step file and used geoUNED. The input file for OpenMC is propely created, but the units are wrong. The cylinder in OpenMC has a radius of 50 cm and a height of 50 cm (It should be 5 cm radius and 5 cm height).

It seems that OpenMC units are not properly converted. In file GEOUNED/src/GEOUNED/Write/Functions.py, in function MCNPSurface, units are converted from mm to cm. Serpent function seems OK too. However, in function OpenMCSurface this conversion is not done. 

I attach the FreeCAD and step files, as well as the python generated by geouned.

[geounedUnits.zip](https://github.com/GEOUNED-org/GEOUNED/files/14999005/geounedUnits.zip)

# To Reproduce
1. Run geouned in the attached files
2. See the generated python dimensions and the dimensions in the freecad file.

# Expected behavior
Units should be converted to cm for OpenMC inputs, as they are for MCNP.

# Error message
No error message

# Please complete the following information):
 - OS: Linux
 - GEOUNED version: c426387987ab7975c11ba4d72be847c61d29138d
 - Python version: 3.10.12

**Comment by psauvan** [comment]
Fixed!!!
The error was introduced during the PHITS export implementation.
