### ISSUE TITLE
[BUG] - CSG model different when identical conversion repeated

### ISSUE THREAD

**Issue by shimwell** [GEOUNED-org/GEOUNED#89]
# Describe the bug
Converting the same stp file twice with the same config results in different values for the surface coefficients and cells enclosures.

I made a config.ini and ran it twice in the same python script. Saving the output converted CSG model to two different text files. I compared the two files and they are different when I was expecting them to be the same

# To Reproduce
Run this script and look at first_run.mcnp and second_run.mcnp files produced. Meld is a nice tool for doing this or VScode can also compare two fiels side by side.
```python
from pathlib import Path
from geouned import GEOUNED
def make_template(
    input_step_file,
    output_stem
):
    
    return (
        "[Files]\n"
        "title = 'Input Test'\n"
        f"stepFile = {input_step_file}\n"
        f"geometryName = {output_stem}\n"
        "outFormat = ('mcnp', 'openMC_XML')\n"
        "[Parameters]\n"
        "compSolids = False\n"
        "volCARD = False\n"
        "volSDEF = True\n"
        "voidGen = True\n"
        "dummyMat = True\n"
        "minVoidSize = 100\n"
        "cellSummaryFile = False\n"
        "cellCommentFile = False\n"
        "debug = False\n"
        "simplify = no\n"
        "[Options]\n"
        "forceCylinder = False\n"
        "splitTolerance = 0\n"
        "newSplitPlane = True\n"
        "nPlaneReverse = 0\n"
        "[Tolerances]\n"
        "relativePrecision = 1e-6"  # here we make u new number for relativePrecision
    )

path_to_cad = Path("testing/inputSTEP")
step_files = list(path_to_cad.rglob("*.stp")) + list(path_to_cad.rglob("*.step"))
input_step_file = step_files[2]

with open("config1.ini", mode="w") as file:
    file.write(make_template(input_step_file,'first_run'))

GEO = GEOUNED('config1.ini')
GEO.SetOptions()
GEO.Start()

with open("config2.ini", mode="w") as file:
    file.write(make_template(input_step_file,'second_run'))

GEO = GEOUNED('config2.ini')
GEO.SetOptions()
GEO.Start()
```

**IMPORTANT**
If you failed to convert a specific geometry, please isolate the geometry features producing the bug (ideally a single body), save it as a STEP file and attach it to this issue. Include also all the files used in the conversion as well as the GEOUNED version used.

# Expected behavior
Files should be the same, appart from the timestamp

# Error message
no error message produced

# Screenshots
![Screenshot 2024-04-25 190040](https://github.com/GEOUNED-org/GEOUNED/assets/8583900/c5d353ba-052b-46d1-be2d-52bea522f02b)

# Please complete the following information):
 - OS: ubuntu 22.04
 - GEOUNED dev branch
 - Python version 3.10

**Comment by alexvalentine94** [comment]
expected behaviour based on precision in independent FreeCAD conversion.
