### ISSUE TITLE
[BUG] - Issue with converting bodies containing tori with 'forceCylinder' set to 'True'

### ISSUE THREAD

**Issue by teade** [GEOUNED-org/GEOUNED#94]
# Describe the bug
There is an issue converting toridal surfaces with 'forceCylinders' set to 'True'. See images of CAD and conversion below. 

<img src="https://github.com/GEOUNED-org/GEOUNED/assets/37874718/0243b2df-00af-487c-819b-07e3751f1a06" width="400" height="400">
<img src="https://github.com/GEOUNED-org/GEOUNED/assets/37874718/dbb82d2b-3a7e-41f1-b7ba-037c31202395" width="400" height="400">

This seems to be due to the radius of the cylinder limiting the extent of the toroidal surface being set to the minimum of d1 or d2.

# To Reproduce
for example:
1. Use attached stp file: [example_tori.zip](https://github.com/GEOUNED-org/GEOUNED/files/15095762/example_tori.zip)
3. Use current main branch commit: https://github.com/GEOUNED-org/GEOUNED/commit/bc74e7ef28a50290fdfd3847cea7c1956fea3418
4. Ensure that 'forceCylinders' option is set to True (this seems to be the default)

# Expected behavior
This is the geometry you would expect to see. 

<img src="https://github.com/GEOUNED-org/GEOUNED/assets/37874718/a4bc9096-8bd4-4f51-a3ef-76f529d3bf9a" width="400" height="400">

It appears that when inSurf is true the maximum value of d1 or d2 is required.

**Comment by psauvan** [comment]
Perhaps, it is better to remove the "forceCylinder" option and use only cones to define the annex torii surfaces.
What do you think? Do you see any reason to keep cylinders as annex surface for torus (of course except in the case in which the cone parameters degenerate to a cylinder)?

**Comment by alexvalentine94** [comment]
New issue to be raised on latest comments.
